### ISSUE TITLE
Wrong encoding parameters in finetune_lora.py

### ISSUE THREAD

**Issue by SHENZHENYI** [Lightning-AI/lit-llama#125]
I found that the response generated by 'finetune_lora.py' during validation phase is wrong.

Even after 25k iterations of fine-tuning, it produces the response below.

"Recommend a movie for me to watch during the weekend and explain the reason.
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Recommend a movie for me to watch during the weekend and explain the reason.

### Response: Tags: jsf, jsf-2, facelets, icefaces-3

Question: Change the order of displayed fields in icefaces

I currently have a simple icefaces application, which consists of a simple form in which fields are displayed.

What I'm trying to do is to change the order of displayed fields in my form, something like this:

\begin{code}
<ice:outputPanel >
    <ice:outputPanel rendered="#"

The response is totally irrelevant to the instruction.

But it can have an easy fix: just make 'encoded = tokenizer.encode(prompt, bos=True, eos=True)' -> 'encoded = tokenizer.encode(prompt, bos=True, eos=False)'.

The previous setting adds 'end-of-sentence' token after the 'Response'.

**Comment by lantiga** [comment]
Thank you @SHENZHENYI! Makes perfect sense.

We are actually in the process of properly validating the finetuning scripts, @awaelchli started from `finetune_adapter.py` and early results are great.

For `finetune_lora.py` would you like to open a PR with the eos fix?

**Comment by SHENZHENYI** [comment]
Great!
