### ISSUE TITLE
Terminate early at EOS when performing inference

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lit-llama#130]
Our inference script (generate.py) and instruct.py (if #128 lands) currently generate text up to the max length. However, the model can generate an EOS token any time. We should stop the sequence and truncate it. In #128 this truncation was done after generating the full sequence, but we could already early stop during [the for loop](https://github.com/Lightning-AI/lit-llama/blob/094fa95523dc3f157aa357c8d1beaee6377f4459/generate.py#L42).

**Comment by carmocca** [comment]
Different generations in the batch might generate the EOS at different points. Since the generation is batched, maybe we just want to stop the for loop once all generations have generated one EOS. I'm not sure if this would be faster under compilation as it adds a data dependency

**Comment by SHENZHENYI** [comment]
Yea. I noticed it today when I do inference. As I saw Russian (maybe?) after I prompted a rather regular instruction.

I fixed this problem by early-stopping the for loop when the next_token == tokenizer.eos_id. But my current implementation only works when batch_size == 1. Don't know whether you want to support when the batch_size is larger.

The original generation:
'''
### Instruction:
Tell me about the president of Mexico in 2019.

### Response:Most of the information you may wish to know about President Andrés Manuel López Obrador, commonly known as Andrés Manuel or AMLO, is already available in many online sources.

A brief summary of the current president of Mexico is as follows:

- Educated as lawyer and public security specialist

- Political career: he was a Member of the Mexican Congress between 2000 and 2005.

- He served as the Mayor of Mexico City from 2000 to 2005.

- Elected president of Mexico in the general election of 2018.

- Assuming the presidential term on 1 December 2018, with a majority in both the Chamber of Deputies and the Senate.

- In 2020 was recognized by the United Nations as a Champion of the Sustainable Development Goals for the work done in thearea of public health against COVID19.

- Has been a vocal opponent of human rights violations and corruption, ensuring that justice is always served.

Overall, President López Obrador is known for his integrity and for his commitment to improving the lives of Latin Americans. If you want more detailed information, I suggest you consult any online reliable source that provides information on this subject. # Воспитание эмоций

Воспитание эмоций, то же, что и эмоциональное воспитание, это непрерывное внимание и оборачивание личности, с целью ответана потребности и желания ребенка или подростка, их развития, а также формированию позитивных эмоций. Воспитание эмоций включает в себя обучение индивиду, позволяющее ему отвечать на необходимости изменений, каузации, и идентификации с требуемой моральным поведением и может включать в себя:

* Программа формирования/развития/утверждения адекватной эмоциональной чувствительности и реакции
* Стимуляция проявления корректных эмоций
* Формирование мотивации
'''

After the 'early stopping':
'''
### Instruction:

Tell me about the president of Mexico in 2019.

### Response:

Most of the information you may wish to know about President Andrés Manuel López Obrador, commonly known as Andrés Manuel or AMLO, is already available in many online sources.

A brief summary of the current president of Mexico is as follows:

- Educated as lawyer and public security specialist
- Political career: he was a Member of the Mexican Congress between 2000 and 2005.
- He served as the Mayor of Mexico City from 2000 to 2005.
- Elected president of Mexico in the general election of 2018.
- Assuming the presidential term on 1 December 2018, with a majority in both the Chamber of Deputies and the Senate.
- In 2020 was recognized by the United Nations as a Champion of the Sustainable Development Goals for his work towards theimplementation of the SDGs agenda.
- Successively, he reached an agreement with the business community to share the blame for the economic catastrophe of theearly 2000s and discharge the credit and debt for its clients in 2005.
'''
