### ISSUE TITLE
How to use training LLaMA with train.py, what format of training data needs to be provided?

### ISSUE THREAD

**Issue by delltower** [Lightning-AI/lit-llama#134]

**Comment by awaelchli** [comment]
@delltower Our script is not set up to load the data for training LLaMA like in the original paper. The current script is just a skeleton and as a placeholder there is simple data loading code for shakespeare. You can have a look at https://github.com/Lightning-AI/lit-llama/blob/main/scripts/prepare_shakespeare.py where we simply tokenize the entire text data at once and serialize it as a tensor. This preparation is done once.
And then the training script simply loads this array of data and forms batches of random subsequences:
https://github.com/Lightning-AI/lit-llama/blob/e9afbc6836fa957343db019bbc0f82cb717cbcff/train.py#L145-L156

The preparation and loading of the full data as in the paper would be similar. The only major difference would be that the dataset wouldn't be loaded into memory in its entirety. 

I hope this helps.

**Comment by mohataher** [comment]
Great work @awaelchli, I'm curious to see whether the current implementation could be used to fine tune on a large dataset of 10GB size. 

My thought process here is to leverage the code on https://github.com/Lightning-AI/lit-llama/blob/main/scripts/prepare_shakespeare.py and re-use it load the 10GB dataset. Is that doable?

**Comment by awaelchli** [comment]
Yes this should still work for the 10GB dataset. You could preprocess it the same way as prepare_shakespeare.py. In the training script, it uses `np.memmap` so you shouldn't see any CPU memory issues. In case the dataloading becomes a bottleneck (for large batch sizes or sequence length), you could also put the get_batch function into a `torch.utils.data.Dataset` and use the `torch.utils.data.DataLoader` with `num_workers > 1`.

**Comment by lantiga** [comment]
Follow #157 (introduced indexed_dataset from megatron and added red pajama data conversion) and #161 (building a pre-training script based on the red pajama data)

**Comment by lantiga** [comment]
#209 landed, feel free to take a look
The format is now PackedDataset, I'll write a howto in a few hours.
