### ISSUE TITLE
Can't use converted 13/30/65b models

### ISSUE THREAD

**Issue by dnhkng** [Lightning-AI/lit-llama#141]
Hi,

I'm probably doing something dumb, but I used the "convert_hf_checkpoint.py" to convert all the HF models. After the conversions, I have model sizes of 27Gb, 52Gb, 130Gb and 260Gb.

I checked, and I used the following commands for the conversions:

```
 python scripts/convert_hf_checkpoint.py --hf_checkpoint_path /mnt/data/llama_hf_models/llama-13b-hf  --model_size 13B
 python scripts/convert_hf_checkpoint.py --hf_checkpoint_path /mnt/data/llama_hf_models/llama-30b-hf  --model_size 30B
 python scripts/convert_hf_checkpoint.py --hf_checkpoint_path /mnt/data/llama_hf_models/llama-65b-hf  --model_size 65B
 python scripts/convert_hf_checkpoint.py --hf_checkpoint_path /mnt/data/llama_hf_models/llama-30b-hf  --model_size 30B

```

The 7B model works flawlessly, and I was able to fine-tune and quantise the model. However, for all the other sizes, I get error like this when I attempt to use the model in any way:
```
	size mismatch for transformer.h.29.rms_2.scale: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for transformer.h.30.rms_1.scale: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for transformer.h.30.rms_2.scale: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for transformer.h.31.rms_1.scale: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for transformer.h.31.rms_2.scale: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).
	size mismatch for transformer.ln_f.scale: copying a param with shape torch.Size([5120]) from checkpoint, the shape in current model is torch.Size([4096]).
```

It looks like some of the model parameters are read incorrectly, but I'm not sure why. Any help would be appreciated!

**Comment by lantiga** [comment]
Thanks for reporting this @dnhkng, I'll check this in the next few hours

**Comment by lantiga** [comment]
When is the error showing up? Conversion time or loading time after conversion?

**Comment by dnhkng** [comment]
The conversion seems to run OK. The 33 and 65Gb models use a lot of ram 2-300Gb, but I'm using a system the 8x V100 and 640 Gb ram 👍

The model sizes are the output from the conversion. When I try use them (inference, training or quantisation), the i get the error reported on size mismatch.

**Comment by lantiga** [comment]
Ongoing work on #122
It should also greatly decrease memory use as well as allow you to generate bfloat16 weights without allocating the full model

**Comment by lantiga** [comment]
@dnhkng #122 is ready

I tested it and it generates viable checkpoints.

To convert to `bfloat16` (if you omit it will convert to `float32`):

```
python scripts/convert_hf_checkpoint.py --hf_checkpoint_path checkpoints/llama-hf/llama-13b-hf --lit_checkpoint lit-llama.pth --model_size 13B --dtype bfloat16
```

It's much faster than before and it uses less memory.

To generate:

```
python generate.py --dtype bfloat16 --prompt "Hello, my name is" --checkpoint_path foo.pth --model_size 13B
```

In your case I think the error arose because you didn't specify `--model_size 13B` when invoking `generate.py`

**Comment by dnhkng** [comment]
Testing it now, I'll report back after the 13B version

**Comment by lantiga** [comment]
Great, thank you for letting me know @dnhkng

**Comment by dnhkng** [comment]
Sorry to reopen this, but I just found another (potential) issue:
but after reaching the model level:
`0 mlp.c_fc2 collecting stats quantizing time 22s quantization error 351.9`
I get an out-of-memory error.
```
OutOfMemoryError: CUDA out of memory. Tried to allocate 730.00 MiB (GPU 0; 31.75 GiB total capacity; 29.65 GiB already allocated; 82.69 MiB free; 30.68 GiB reserved in total by PyTorch) 
If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Although I can in theory quantize 13B, in practice I can't even with 40Gb VRAM.  I can't even start on the 30B model, as I get OOM instantly.

I am using the command:
`python quantize.py --model_size 30B --checkpoint_path checkpoints/lit-llama/30B/lit-llama-30b.pth --tokenizer_path checkpoints/lit-llama/tokenizer.model --output_path llama-30b-gptq.4bit.pt --dtype bfloat16  --quantize gptq.int4`
This is after using the new push, so I think the models are already in BF16 (the 30B model is now only 65Gb).
