### ISSUE TITLE
save_checkpoint_function unused?

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-llama#186]
In [finetune_lora.py](https://github.com/Lightning-AI/lit-llama/blob/main/finetune_lora.py), the `save_model_checkpoint` utility is imported but unused:

https://github.com/Lightning-AI/lit-llama/blob/a1ff82d46caf14bb5386ec94b385b9e7ddf81357/finetune_lora.py#L18

Instead if saves the model like so

https://github.com/Lightning-AI/lit-llama/blob/a1ff82d46caf14bb5386ec94b385b9e7ddf81357/finetune_lora.py#L76

Is this intentional, i.e., does the `save_checkpoint_function` only work for adapters?

**Comment by awaelchli** [comment]
Yes, the unused import is accidental. The `save_model_checkpoint` is currently only used to add special support for multi-gpu training with deepspeed and fsdp for the `finetune_adapter.py` script.
