### ISSUE TITLE
Is it possible to merge the code with Huggingface?

### ISSUE THREAD

**Issue by richardsun-voyager** [Lightning-AI/lit-llama#203]
Dear developers, thanks very much for sharing this project, which helps me to run an LLM on my single-GPU machine efficiently. As Huggingface also offers a range of Transformer-based pre-trained models, is it possible to merge this lighting package with huggingface tools?

**Comment by lantiga** [comment]
Hey @richardsun-voyager, what would be your ideal integration?

In the spirit of keeping things simple and clear we are not currently planning to integrate with the Transformers library. Our goal is not to support many different models, but rather to provide a clean and efficient codebase on the one model we support per repository.

Note that you can import HF weights into lit-llama using https://github.com/Lightning-AI/lit-llama/blob/main/scripts/convert_hf_checkpoint.py

Howto here: https://github.com/Lightning-AI/lit-llama/blob/main/howto/download_weights.md

**Comment by richardsun-voyager** [comment]
Hi Lantiga

> Hey @richardsun-voyager, what would be your ideal integration?
> 
> In the spirit of keeping things simple and clear we are not currently planning to integrate with the Transformers library. Our goal is not to support many different models, but rather to provide a clean and efficient codebase on the one model we support per repository.
> 
> Note that you can import HF weights into lit-llama using https://github.com/Lightning-AI/lit-llama/blob/main/scripts/convert_hf_checkpoint.py
> 
> Howto here: https://github.com/Lightning-AI/lit-llama/blob/main/howto/download_weights.md

**Comment by richardsun-voyager** [comment]
Hi @lantiga,
Thanks very much for your reply! Now, I am clear about how to implement your code on my machine. Hope my question won't offend you as it conflicts with your idea.
