### ISSUE TITLE
Avoid complex usage to compute RoPE

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lit-llama#21]
This will allow using `torch.compile`: https://github.com/Lightning-AI/lightning-llama/pull/17

**Comment by lantiga** [comment]
So for reference, we can already avoid the complex calls based on the original RoPE implementation - it's there in the tests already. The caveat is that numerical differences make generation degrade when loading pre-trained weights (it will be fine for pre-training).

We need to investigate further (anyone volunteering)?

**Comment by carmocca** [comment]
Right, the problem to solve is: "Can we make the alternative implementation numerically equivalent"?

For anybody trying, you can remove the `not` here to try: https://github.com/Lightning-AI/lit-llama/blob/f808df1971cbac345b3d8de263a251374a53d5e9/tests/test_rope.py#L67-L71

**Comment by lantiga** [comment]
Solved by #174
