### ISSUE TITLE
Fine-tuning on multiple GPUs

### ISSUE THREAD

**Issue by willbairdtechnology** [Lightning-AI/lit-llama#231]
Hi! Thanks for all the work that has been put into this project. I'm curious to know if it's possible to fine-tune a >30B model with multiple GPUs? Currently running 4 x A100 80GB. Any insight would be greatly appreciated! I was considering implementing some DDP if it's not already implemented.

Thanks in advance for any advice!

**Comment by icwhite** [comment]
Hello willbairdtechnology! Did you make any progress on this? I am in a similar situation now!
