### ISSUE TITLE
Error while running  scripts/prepare_alpaca.py on windows 11

### ISSUE THREAD

**Issue by All-Ki** [Lightning-AI/lit-llama#239]
Just downloaded weights and converted them , and i get this error whilst doing  scripts/prepare_alpaca.py : (Running generate works though ) 
[log.txt](https://github.com/Lightning-AI/lit-llama/files/11421626/log.txt)

JSONDecodeError: Expecting value: line 1 column 1 (char 0) 

Joining logs as file because they render too poorly here

**Comment by carmocca** [comment]
Can you check the contents of this file? https://github.com/Lightning-AI/lit-llama/blob/02dcdaf45881585045ed93a74e417415d328e538/scripts/prepare_alpaca.py#L38. It's probably empty.

By default, the path is `data/alpaca/alpaca_data_cleaned_archive.json`

If you remove it, the script will try to download it again: https://github.com/Lightning-AI/lit-llama/blob/02dcdaf45881585045ed93a74e417415d328e538/scripts/prepare_alpaca.py#L68-L73

**Comment by All-Ki** [comment]
That was the issue, thanks ! I think it happened because i used the prepare_alpaca script with missplaced models folder , i think a good fix would be to check if the file is empty before trying to load it ?

**Comment by carmocca** [comment]
The JSONDecodeError is telling you that the file is empty: "expected value: line 1"

Glad you resolved the issue :)
