### ISSUE TITLE
error when i convert the weight

### ISSUE THREAD

**Issue by papipsycho** [Lightning-AI/lit-llama#244]
hello guys, 

i have an issue when i convert the weights i just got the error message : 
Killed 
and nothing more  there is any verbose mode to understand what's happend ?

full log

~/lit-llama$ python3 scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/open-llama/7B/open_llama_7b_preview_300bt_transformers_weights --model_size 7B
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
Initializing lit-llama
Processing pytorch_model-00001-of-00002.bin
Killed

**Comment by awaelchli** [comment]
Hi @papipsycho 

On what machine did you execute this?

**Comment by carmocca** [comment]
I have had this happen to me when I run out of memory. I think you need at least 26 GBs of memory.

I think we should clarify these requirements in our howtos

**Comment by ashutosh-dwivedi-e3502** [comment]
I have the same issue. I am running the script on a A10 graphics card (24 GB) of graphics memory, with a g5dn.4xlarge instance.
Here's the output from the run : 

```
(python) root@0508-054119-7va9hy6i-10-198-85-93:/databricks/driver/lit-llama# python /databricks/driver/lit-llama/scripts/convert_hf_checkpoint.py --checkpoint_dir /dbfs/Shared/llm/checkpoints/open-llama/7B/open_llama_7b_preview_300bt_transformers_weights --model_size 7B --output_dir /databricks/driver/lit-llama/checkpoints/                                                                                                                                               /databricks/python/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
2023-05-11 11:43:24.441285: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-11 11:43:25.029966: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
/databricks/python/lib/python3.9/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(/databricks/python/lib/python3.9/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Initializing lit-llama
Processing pytorch_model-00001-of-00002.bin
Killed
```

**Comment by ashutosh-dwivedi-e3502** [comment]
Can you specify the requirement, is it 26 GB of graphics memory? I am running it on an A10 GPU which has 24 GB of graphics memory.

**Comment by Ro-Ol** [comment]
I ran the conversion script on g4dn.2xlarge, which has 32GiB of RAM and the machine ran out of memory. Am I missing something?

**Comment by lantiga** [comment]
I can successfully convert the 7B checkpoint on a 24BG instance. However larger checkpoints will require more memory.

The real solution here is using lazy loading (and eager unloading), as shown at

https://github.com/Lightning-AI/lit-llama/blob/main/lit_llama/utils.py#L274

Who wants to volunteer? :-)

**Comment by connershoop** [comment]
Chiming in here. In order to run this conversion on WSL (Ubuntu 22.04) I needed to expose 25GB of RAM (since WSL does not expose all of your RAM by default).  Even exposing 20GB of RAM failed with the error:
```
Initializing lit-llama
Processing pytorch_model-00001-of-00002.bin
Killed
```
as mentioned above

**Comment by egeres** [comment]
@connershoop answer almost worked for me, I had to set the memory of WSL to 32Gb instead of 25Gb by editing the `C:\Users\<Username>\.wslconfig` to be

```
[wsl2]
memory=32GB
```

**Comment by carmocca** [comment]
This was resolved by https://github.com/Lightning-AI/lit-llama/pull/326. Converting weights should not require that much RAM anymore
