### ISSUE TITLE
"generate_prompt" call appears to be missing in generate_full.py

### ISSUE THREAD

**Issue by wlsdnen** [Lightning-AI/lit-llama#246]
Before calling the generate function in the 'generate_full.py' file (line 129), shouldn't we call the generate_prompt function on the prompt? I mean, something like this:

```
tokenizer = Tokenizer(tokenizer_path)
sample = {"instruction": prompt, "input": input}
prompt = generate_prompt(sample)
encoded = tokenizer.encode(prompt, bos=True, eos=False, device=model.device)

```
I have checked that a correct response is generated this way. If this is correct, it appears that an update is needed.

**Comment by awaelchli** [comment]
I agree. Would you like to send an update?

**Comment by wlsdnen** [comment]
> I agree. Would you like to send an update?

Thank you for your feedback. I will send an update to reflect this change.
