### ISSUE TITLE
weight decay

### ISSUE THREAD

**Issue by vgoklani** [Lightning-AI/lit-llama#254]
Please correct me i'm wrong, but it appears that you are applying `weight-decay` to all of the layers:

https://github.com/Lightning-AI/lit-llama/blob/main/train_redpajama.py#L104

It was my understanding that `weight-decay` should not be applied to the `LayerNorm`, `Embedding`, or to any `bias` terms. 

Please let me know if I'm mistaken. thanks!

**Comment by carmocca** [comment]
Good point. At least, nanoGPT did it: https://github.com/karpathy/nanoGPT/commit/7fe4a099ad2a4654f96a51c0736ecf347149c34c ([ref](https://github.com/karpathy/minGPT/pull/24#issuecomment-679316025))
