### ISSUE TITLE
How to run the code on a specific gpu device?

### ISSUE THREAD

**Issue by bf-yang** [Lightning-AI/lit-llama#267]
For example, I want to run the code on GPU 1, like: torch.cuda.set_device(1).
What should I do?
Thanks.

**Comment by wlsdnen** [comment]
os.environ["CUDA_VISIBLE_DEVICES"]="1"

**Comment by bf-yang** [comment]
> 

I tried it but it seems that my code still runs on GPU0 as it reports an error: "GPU 0 has a total capacity...."

**Comment by timothylimyl** [comment]
You can try just putting it in front of your terminal command. For example, 

`CUDA_VISIBLE_DEVICES=0 python3 finetune_lora.py`

**Comment by ARROGANT666** [comment]
export CUDA_VISIBLE_DEVICES=1

**Comment by rasbt** [comment]
Yes, that's what I usually do as well. Let me add multi-GPU example as well. So, for example, if you have `devices=4` in the script and want to run on the first, third, fifth, and seventh GPU in a machine, you can do

```bash
CUDA_VISIBLE_DEVICES=0,2,4,6 python finetune/lora.py ...
```
