### ISSUE TITLE
finetune scripts assume that the tokenizer is stored into "checkpoints/lit-llama/tokenizer.model"

### ISSUE THREAD

**Issue by Freddavide** [Lightning-AI/lit-llama#269]
I discovered that the fine-tune scripts assume that the tokenizer is stored into "checkpoints/lit-llama/tokenizer.model".
I think It would beneficial to include the tokenizer_path as an argument for the scripts, as in the generate.py script.

For example in finetune/lora.py at line 134

def generate_response(model, instruction):
    tokenizer = Tokenizer("checkpoints/lit-llama/tokenizer.model")

**Comment by lantiga** [comment]
Fixed by #285, thanks for filing the issue!
