### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by backatonesJ** [Lightning-AI/lit-llama#283]
I want to finetune on my own dataset, but it failed：
File "/home/ubuntu/miniconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Can you someone please guide how to solve this problem
Thank You!

**Comment by carmocca** [comment]
Which script are you running? 

See also this report: https://github.com/Lightning-AI/lit-llama/issues/239

**Comment by backatonesJ** [comment]
> Which script are you running?
> 
> See also this report: #239

I am runing the prepare_mydata.py

**Comment by backatonesJ** [comment]
> > Which script are you running?
> > See also this report: #239
> 
> thank u so much!    the problem is solved
