### ISSUE TITLE
How to modify scripts/prepare_mydata.py to read my json data file.

### ISSUE THREAD

**Issue by jxuse** [Lightning-AI/lit-llama#287]
I want to tune on my datasets,but I do not know clearly how to modify scripts/prepare_mydata.py to read my json data file, the scripts/prepare_mydata.py is a copy of  scripts/prepare_alpaca.py.
Can you someone please guide how to do?
Thank you!

**Comment by Freddavide** [comment]
Hi! The easiest thing you can do is:
- comment out line 39

`#download(file_path)`

- call the script passing as destination_path the folder in which your json file is stored, and as data_file_name the name of your json file

`python ./scripts/prepare_my_data.py --destination_path /path/to/your/data --data_file_name your_data_file_name.json`

**Comment by jxuse** [comment]
NICE！I got a good idea from your promtp .Thank you so much!

**Comment by carmocca** [comment]
Looks resolved! Closing
