### ISSUE TITLE
RuntimeError while running finetune_lora.py

### ISSUE THREAD

**Issue by Abecid** [Lightning-AI/lit-llama#288]
RuntimeError: Failed to import transformers.modeling_utils because of the following error
/usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

Python 3.8.10
torch 2.0.1+cu117
transformers 4.29.2

**Comment by lantiga** [comment]
This is weird because we are not requiring `transformers` for the project.
Can you try in a fresh environment?

**Comment by Abecid** [comment]
Yep I just crated a different container. It must have been a conflict with other libraries installed previously for other repos
