### ISSUE TITLE
about the vocab size

### ISSUE THREAD

**Issue by lucasjinreal** [Lightning-AI/lit-llama#289]
it some where says using open-llama which have 40000 vocabsize, but from the config, I saw it was 32000, is there a bias here?

**Comment by rasbt** [comment]
The 32,000 should be based on the original LLaMA model. If you use the pretrained weights, I'd say you have to go with that otherwise you'd have to retrain it on the new/larger vocab.

**Comment by lucasjinreal** [comment]
@rasbt But I downloaded open-llama's tokenizer model found they actually is 32k vocab size.

![image](https://github.com/Lightning-AI/lit-llama/assets/21303438/4691d6b9-4e2f-4b63-80c1-61cb85dccc1b)

**Comment by rasbt** [comment]
Oh nice, so it's basically no issue / discrepancy here when I understand correctly? 😊

**Comment by lucasjinreal** [comment]
sorry, its only 32k actually in openllama, I missed remembered.
