### ISSUE TITLE
Download script saves symlinks to hf cache folder

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lit-llama#295]
Our download script calls the HF API to download the checkpoint snapshot. This lands in the user's huggingface cache folder (usually in ~/.cache/huggingface) and then symlinks the files to the target folder. 

On cloud instances where the home folder gets deleted, and only a subfolder is persisted, the checkpoint files get lost and the symlinks become invalid.

To reproduce (from howto):
```
python scripts/download.py --repo_id openlm-research/open_llama_7b_400bt_preview --local_dir checkpoints/open-llama/7B
```

My proposal is to move the files from the cache folder to the actual checkpoint folder specified by the user, without symlinks.

**Comment by lantiga** [comment]
Totally agree with the proposal.

**Comment by carmocca** [comment]
Theres a `local_dir_use_symlinks=False` argument we can set for this
