### ISSUE TITLE
Gating factor in Adapter for multiple heads

### ISSUE THREAD

**Issue by Andrei-Aksionov** [Lightning-AI/lit-llama#296]
Hi there 👋 

This is a semi-issue/semi-question: why do we use in Adapter a single learnable parameter for gating factor?
https://github.com/Lightning-AI/lit-llama/blob/7e72448f9b307e95f502249484cc52e6b90ad5ba/lit_llama/adapter.py#L40

In the [paper](https://arxiv.org/pdf/2303.16199.pdf) in section 3.2 (right before formula 8) it says:
> In practice, we adopt multiple gl to be independently learned for different heads of the attention mechanism

If to take a look at the official implementation different gating factors for each head are [learned](
https://github.com/ZrrSkywalker/LLaMA-Adapter/blob/fd4fb6cb8f947c941c5ec3b9dd6342b4a06ed72/llama_adapter_v2_chat65b/llama/model.py#L119):
```python
self.gate = torch.nn.Parameter(torch.zeros(1, args.n_heads, 1, 1))
```

Shouldn't it be also implemented here?
Or there is a reason for it: 
1. No difference in practice
2. Some issues with licensing like it was stated in [this](https://github.com/Lightning-AI/lit-llama/issues/263) issue?

**Comment by rasbt** [comment]
That's a good point. I agree with you here. Also, I just gave it a try and it seems like it doesn't really make a difference in practice. In my opinion, it would be nice to have the implementation closer to the one in the paper.

**Comment by Andrei-Aksionov** [comment]
Thanks @rasbt for testing it and opening PR.
