### ISSUE TITLE
AssertionError checkpoint_path

### ISSUE THREAD

**Issue by artemisep** [Lightning-AI/lit-llama#304]
when running python generate.py --prompt "Hello, my name is" to test downloaded weights,
return the following error msg: AssertionError: checkpoints/lit-llama/7B/lit-llama.pth
However, there are two model files and they are in the following dir: 
checkpoints/open-llama/7B/pytorch_model-00001-of-00002.bin
checkpoints/open-llama/7B/pytorch_model-00002-of-00002.bin

**Comment by rasbt** [comment]
Hi there,

after downloading, there's usually a weight conversion step required (via https://github.com/Lightning-AI/lit-llama/blob/main/howto/download_weights.md). Have you done this step?

It's 

```python
python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/open-llama/7B --model_size 7B
```
