### ISSUE TITLE
Will lit-llama support QLoRA?

### ISSUE THREAD

**Issue by taomanwai** [Lightning-AI/lit-llama#328]
It claims able to fine tune 65B LLaMA on a 48GB VRAM GPU.

**Comment by lantiga** [comment]
Yes! As soon as we understand what branch from bitsandbytes to use :-)

**Comment by fishelegs** [comment]
hi is there any progress?

**Comment by carmocca** [comment]
Lit-GPT supports this: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/finetune_lora.md
