### ISSUE TITLE
using GPTQ-style int4 quantization  when conversions of the weights , I encountered an error

### ISSUE THREAD

**Issue by jxrjlxc02** [Lightning-AI/lit-llama#341]
Operation note：
You can also use GPTQ-style int4 quantization, but this needs conversions of the weights first:
`python quantize/gptq.py --checkpoint_path /root/autodl-tmp/lxc/lit-llama/checkpoints/lit-llama/7B/lit-llama.pth --tokenizer_path /root/autodl-tmp/lxc/lit-llama/checkpoints/lit-llama/tokenizer.model --output_path /root/autodl-tmp/lxc/lit-llama/checkpoints/gptq_model_4bit/llama-7b-gptq.4bit.pth --dtype bfloat16  --quantize gptq.int4`

torch version : torch                    2.1.0.dev20230529+cu118

Errors encountered：
`python quantize/gptq.py --checkpoint_path /root/autodl-tmp/lxc/lit-llama/checkpoints/lit-llama/7B/lit-llama.pth --tokenizer_path /root/autodl-tmp/lxc/lit-llama/checkpoints/lit-llama/tokenizer.model --output_path /root/autodl-tmp/lxc/lit-llama/checkpoints/gptq_model_4bit/llama-7b-gptq.4bit.pth --dtype bfloat16  --quantize gptq.int4
Loading model ...
Time to load model: 21.05 seconds.
Found cached dataset json (/root/.cache/huggingface/datasets/allenai___json/allenai--c4-6fbe877195f42de5/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
Getting inputs for first block
LLaMA(
  (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
  (transformer): ModuleDict(
    (wte): Embedding(32000, 4096)
    (h): ModuleList(
      (0-31): 32 x Block(
        (rms_1): RMSNorm()
        (attn): CausalSelfAttention(
          (c_attn): Linear(in_features=4096, out_features=12288, bias=False)
          (c_proj): Linear(in_features=4096, out_features=4096, bias=False)
        )
        (rms_2): RMSNorm()
        (mlp): MLP(
          (c_fc1): Linear(in_features=4096, out_features=11008, bias=False)
          (c_fc2): Linear(in_features=4096, out_features=11008, bias=False)
          (c_proj): Linear(in_features=11008, out_features=4096, bias=False)
        )
      )
    )
    (ln_f): RMSNorm()
  )
)
LLaMAConfig(block_size=2048, vocab_size=32000, padded_vocab_size=32000, n_layer=32, n_head=32, n_embd=4096)
Starting to quantize blocks
0 attn.c_attn collecting stats Traceback (most recent call last):
  File "quantize/gptq.py", line 229, in <module>
    CLI(main)
  File "/root/autodl-tmp/lxc/lit-llama/.venv/lib/python3.8/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/root/autodl-tmp/lxc/lit-llama/.venv/lib/python3.8/site-packages/jsonargparse/cli.py", line 138, in _run_component
    return component(**cfg)
  File "quantize/gptq.py", line 210, in main
    llama_blockwise_quantization(model, encoded_text, device, bits=bits)
  File "/root/autodl-tmp/lxc/lit-llama/.venv/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "quantize/gptq.py", line 90, in llama_blockwise_quantization
    outs[j : j + 1] = block(inps[j : j + 1])
  File "/root/autodl-tmp/lxc/lit-llama/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/autodl-tmp/lxc/lit-llama/.venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: **forward() missing 3 required positional arguments: 'rope', 'mask', and 'max_seq_length'**`

![image](https://github.com/Lightning-AI/lit-llama/assets/66405878/d423ee7e-ca40-4dd9-a0af-1fae0acd370b)

**Comment by carmocca** [comment]
Thanks for reporting! Let me fix this.
