### ISSUE TITLE
Pretraining code: what happens when the document length is larger than the max sequence length of the model?

### ISSUE THREAD

**Issue by LamOne1** [Lightning-AI/lit-llama#363]
Hello,

What happens when the document's length is larger than the max sequence length of the model? Does the model ignore the rest? or is it fed to the model as another example?

**Comment by awaelchli** [comment]
Hey @LamMoh1 
Given the title, I assume your question is about pretraining. So in pretraining, we always only sample subsequences of exactly the length of "max sequence length" (also known as context size) and feed that to the model. In pretraining, there is no "document" structure: The entire internet could be seen as one single document of text from which we sample subsequences. 

If you want to get more familiar with training LLMs, here are some resources I can recommend:
DL course: https://lightning.ai/pages/courses/deep-learning-fundamentals/unit-8.0-natural-language-processing-and-large-language-models/
Karpathy's GPT from scratch course: https://youtu.be/kCc8FmEb1nY?t=867 (here he explains what I wrote above)

**Comment by awaelchli** [comment]
If you have more questions like these, feel free to join our Discord where everyone can learn together: https://discord.gg/XncpTy7DSt

**Comment by LamOne1** [comment]
Thank you @awaelchli !!!!
