### ISSUE TITLE
Use finetune/lora.py to fine tune other LLMs

### ISSUE THREAD

**Issue by HaoruSung** [Lightning-AI/lit-llama#366]
Hello,
Can I use the same way as finetune/lora.py to fine tune Vicuna?

**Comment by awaelchli** [comment]
You can use most of the code there yes! The only thing that you need to change is the code in `lit_llama/lora.py`. You basically need to replace the `nn.Linear` layers in your model with the LoRA Linear and MergedLinear classes, as done [here](https://github.com/Lightning-AI/lit-llama/blob/8aa65ba33e844c283c0a84b9758445fe0c6aab2d/lit_llama/lora.py#L428)  for example.

As a starting point, I recommend studying [this context manager](https://github.com/Lightning-AI/lit-llama/blob/8aa65ba33e844c283c0a84b9758445fe0c6aab2d/lit_llama/lora.py#L448) and work your way up from there. You can see this context manager being applied in the finetune/lora.py file.

**Comment by carmocca** [comment]
Have you tried @HaoruSung? I think it should work since the architecture is the same. Similar issue: https://github.com/Lightning-AI/lit-llama/issues/377

**Comment by HaoruSung** [comment]
> Have you tried @HaoruSung? I think it should work since the architecture is the same. Similar issue: #377

I tried it and so far it seems to be working.
Also how should I resume the checkpoint and continue to use the LoRA fine tuning the model?

thanks, and I really appreciate all the work put into this project!

**Comment by carmocca** [comment]
Can you elaborate? The LoRA script takes a `pretrained_path` argument: https://github.com/Lightning-AI/lit-llama/blob/main/finetune/lora.py#L50. This would be your checkpoint generated from converting Vicuna
