### ISSUE TITLE
Finetuning with LoRa throws an error

### ISSUE THREAD

**Issue by igorcantele** [Lightning-AI/lit-llama#378]
Hello, I'm following this [how to](https://github.com/Lightning-AI/lit-llama/blob/main/howto/finetune_lora.md), but running `lora.py` throws this error:
> RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0
in this line: `ix = torch.randint(len(data), (micro_batch_size,))`

I also tried with `adapter.py` and `adapter_v2.py` obtaining the same result.  
I can't understand what's it caused by.

Data have been generated from a JSON structured like this:
```
[
    {
        "instruction": "instruction",
        "input": "input",
        "output": "output"
    }
]
```

**Comment by carmocca** [comment]
Hi

The error message is telling you that `len(data) == 0`. Since `data` comes from `load_dataset` (https://github.com/Lightning-AI/lit-llama/blob/main/finetune/adapter.py#L226-L229), then it looks like your `*.pt` files are empty.

Can you check that you are generating them correctly?

**Comment by igorcantele** [comment]
I rw-generated the files following [these instructions](https://github.com/Lightning-AI/lit-llama/blob/main/howto/finetune_adapter.md#tune-on-your-dataset) and now it works. Thank you!
