### ISSUE TITLE
TypeError: Fabric.init_module() got an unexpected keyword argument 'empty_init'

### ISSUE THREAD

**Issue by d-dutta** [Lightning-AI/lit-llama#379]
Hi, 

Started to get this error suddenly, it was working before and now all the "generate" scripts are getting this. Not sure why? Any ideas?

Regards
D

**Comment by carmocca** [comment]
Try this

`pip uninstall -y lightning; pip install -r requirements.txt`

**Comment by d-dutta** [comment]
Thanks! Worked! What exactly happened?? Just trying to understand?

**Comment by rasbt** [comment]
Glad it worked! 

@d-dutta the `'`empty_init'` argument is relatively new and was just added to Fabric very recently. So via the above, you essentially installed the newest version from the master branch on GitHub (via `pip install git+https://github.com/Lightning-AI/lightning@master`)
