### ISSUE TITLE
Support for openlm LLaMa 3B

### ISSUE THREAD

**Issue by LamOne1** [Lightning-AI/lit-llama#391]
I’d like your support for adding openlm LLaMa 3B to this repository. Please look to this issue: https://github.com/openlm-research/open_llama/issues/49#issuecomment-1591901584

**Comment by RDouglasSharp** [comment]
In lit_llama/model.py, add "3B":  dict(n_layer=26, n_head=32, n_embd=3200), to llama_configs
In lit_llama/utils.py, add    3000: "3B",   # 3B n_embd=3000 to llama_model_sizes
In scripts/convert_llama_weights_to_hf.py, change if model_size == "7B": to if (model_size == "3B") or (model_size == "7B'):

Finally, to convert the 3B model to a pth, you need to create a pytorch_model.bin.index.json file for convert_llama_weights_to_hf.py:  Below is that file...

{
  "metadata": {
    "total_size": 6802648107
  },
  "weight_map": {
    "lm_head.weight": "pytorch_model.bin",
    "model.embed_tokens.weight": "pytorch_model.bin",
    "model.layers.0.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.0.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.0.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.0.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.0.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.0.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.0.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.0.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.0.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.0.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.1.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.1.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.1.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.1.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.1.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.1.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.1.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.1.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.1.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.1.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.10.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.10.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.10.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.10.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.10.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.10.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.10.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.10.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.10.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.10.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.11.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.11.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.11.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.11.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.11.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.11.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.11.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.11.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.11.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.11.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.12.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.12.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.12.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.12.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.12.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.12.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.12.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.12.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.12.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.12.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.13.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.13.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.13.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.13.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.13.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.13.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.13.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.13.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.13.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.13.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.14.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.14.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.14.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.14.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.14.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.14.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.14.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.14.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.14.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.14.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.15.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.15.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.15.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.15.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.15.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.15.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.15.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.15.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.15.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.15.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.16.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.16.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.16.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.16.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.16.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.16.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.16.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.16.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.16.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.16.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.17.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.17.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.17.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.17.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.17.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.17.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.17.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.17.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.17.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.17.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.18.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.18.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.18.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.18.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.18.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.18.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.18.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.18.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.18.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.18.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.19.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.19.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.19.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.19.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.19.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.19.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.19.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.19.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.19.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.19.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.2.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.2.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.2.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.2.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.2.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.2.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.2.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.2.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.2.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.2.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.20.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.20.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.20.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.20.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.20.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.20.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.20.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.20.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.20.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.20.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.21.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.21.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.21.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.21.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.21.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.21.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.21.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.21.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.21.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.21.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.22.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.22.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.22.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.22.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.22.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.22.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.22.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.22.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.22.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.22.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.23.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.23.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.23.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.23.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.23.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.23.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.23.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.23.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.23.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.23.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.24.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.24.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.24.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.24.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.24.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.24.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.24.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.24.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.24.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.24.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.25.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.25.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.25.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.25.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.25.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.25.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.25.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.25.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.25.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.25.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.3.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.3.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.3.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.3.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.3.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.3.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.3.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.3.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.3.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.3.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.4.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.4.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.4.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.4.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.4.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.4.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.4.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.4.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.4.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.4.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.5.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.5.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.5.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.5.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.5.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.5.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.5.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.5.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.5.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.5.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.6.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.6.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.6.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.6.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.6.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.6.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.6.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.6.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.6.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.6.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.7.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.7.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.7.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.7.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.7.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.7.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.7.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.7.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.7.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.7.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.8.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.8.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.8.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.8.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.8.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.8.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.8.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.8.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.8.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.8.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.layers.9.input_layernorm.weight": "pytorch_model.bin",
    "model.layers.9.mlp.down_proj.weight": "pytorch_model.bin",
    "model.layers.9.mlp.gate_proj.weight": "pytorch_model.bin",
    "model.layers.9.mlp.up_proj.weight": "pytorch_model.bin",
    "model.layers.9.post_attention_layernorm.weight": "pytorch_model.bin",
    "model.layers.9.self_attn.k_proj.weight": "pytorch_model.bin",
    "model.layers.9.self_attn.o_proj.weight": "pytorch_model.bin",
    "model.layers.9.self_attn.q_proj.weight": "pytorch_model.bin",
    "model.layers.9.self_attn.rotary_emb.inv_freq": "pytorch_model.bin",
    "model.layers.9.self_attn.v_proj.weight": "pytorch_model.bin",
    "model.norm.weight": "pytorch_model.bin"
  }
}

**Comment by RDouglasSharp** [comment]
Oops,  also, in lit_llama/model.py class MLP(nn.Module), right after n_hidden = find_multiple(n_hidden, 256) , you need to add 
if n_hidden == 8704:
            n_hidden = 8640
since 8640 is correct for openlm LLaMa 3B, not 8704.

**Comment by carmocca** [comment]
@RDouglasSharp Would you like to open a PR adding support?

**Comment by RDouglasSharp** [comment]
Not super keen to take that on...  I made other changes as well that no-one else nescessarily wants.  And I haven't tested my changes through adapters to see that those areas work.  I just wanted to get initial conversion and pre-training working.

**Comment by LamOne1** [comment]
Thank you @RDouglasSharp! your solution worked with me
