### ISSUE TITLE
full finetune failed when validating 

### ISSUE THREAD

**Issue by LuckyyySTA** [Lightning-AI/lit-llama#406]
When I was using the finetune/full.py training script to perform full fine-tuning on the Alpaca dataset on 4 a100-80g, the following error occurred during validation. The error showed that `input_pos` and `idx_next` were placed on different devices, with input_pos being placed on `idx.device` (CPU) before this line of code was executed(line48 in  lit-llama/generate.py `device, dtype = idx.device, idx.dtype`), while idx_next was placed on CUDA. After I also placed idx_next on `idx.device`, the code ran successfully. 
However, when I traced back the `idx` passed into generate, I found that `idx` is actually `encoded` below. However, according to this line of code `encoded = tokenizer.encode(prompt, bos=True, eos=False, device=model.device)`, encoded is placed on model.device.  I would like to know why `model.device` is CPU instead of CUDA? 

lit-llama/generate.py:84 in generate                                      
│                                                                                                  
│    81 │   │   │   xm.mark_step()                                                                 
│    82 │   │                                                                                      
│    83 │   │   # concatenate the new generation                                                   
│ ❱  84 │   │   idx = idx.index_copy(0, input_pos, idx_next)                                       
│    85 │   │                                                                                      
│    86 │   │   # if <eos> token is triggered, return the output (stop generation)                 
│    87 │   │   if idx_next == eos_id:  

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking 
argument for argument source in method wrapper_CUDA_index_copy)
the same error in cuda:1,2,3

**Comment by hughxiouge** [comment]
How did you solve the problem?
