### ISSUE TITLE
model parameters mismatch for open-llama 3B

### ISSUE THREAD

**Issue by jaykasundra2** [Lightning-AI/lit-llama#408]
I am trying to get the open-llama 3B model work with the library.

I see a following mismatch between huggingface model and the model initiated by `LLaMA` class in all the MLP layer for 3B model.

`Shape mismatch in layer transformer.h.0.mlp.c_fc1.weight: torch.Size([8640, 3200]) vs torch.Size([8704, 3200])`

I was able to load the model with the below change in `model.py` file 
`n_hidden = find_multiple(n_hidden, 256)` to `n_hidden = 8640`

Can someone confirm if this is the correct thing to do or not, and what is the logic behind below code from `model.py`?cause it worked perfectly fine for 7B model but not 3B model 
```        
hidden_dim = 4 * config.n_embd
n_hidden = int(2 * hidden_dim / 3)
n_hidden = find_multiple(n_hidden, 256)
```
 I would like to read more about it.

**Comment by joaopalotti** [comment]
Hi @jaykasundra2, I also wanted to use openllama 3B and I faced the same problem you are mentioning. To fix it, I  created an additional parameter `n_hidden` to the LlamaConfig class replaced the `find_multiple` call with it.

You can find this implementation here: https://github.com/joaopalotti/lit-llama/tree/openllama3B_support
I am happy to create a PR if you want to support openllama 3B and are happy with this solution, lit-llama developers.

**Comment by RDouglasSharp** [comment]
See issue #391 here:   https://github.com/Lightning-AI/lit-llama/issues/391  closed, but someone should actually have implemented it in the codebase before it was closed.
