### ISSUE TITLE
Finetune llama-65b OOM with 8 A100 80GB GPUs

### ISSUE THREAD

**Issue by weilong-web** [Lightning-AI/lit-llama#412]
I'm experiencing an issue while running the lora.py code for finetuning the Llama 65b model with default choices. I have a machine with 8 A100SXM 80GB GPUs. In order to utilize all the GPUs, I changed the device number to 8 and reduced the microbatch size to 1, while keeping everything else the same.

During the first attempt, I encountered a "cuda out of memory" error. I monitored the CPU and GPU usage and noticed that the total CPU RAM memory, which is 2TB, was nearly fully utilized. However, when I tried again, there was no "gpu out of memory" error. I suspect that the CPU may be another limiting factor as well.

If you have successfully finetuned the 65B model without quantization, please let me know.

Thank you for your assistance!

Check #375 as well.

**Comment by AnnaKholkina** [comment]
Hi! Did you solve it? How?
