### ISSUE TITLE
Can we create a small model for dev?

### ISSUE THREAD

**Issue by flyman3046** [Lightning-AI/lit-llama#419]
The smallest model is 7B. Can we create a small one (e.g. 1B, or 0.2B) which can fit into a single GPU for dev purposes and with a small dataset (maybe only wiki data)? I think a small model is much easier for a newcomer to go through the whole process (from preparing data, pre-training, to fine-tuning). Thanks.

**Comment by carmocca** [comment]
If you use lit-gpt, you'll find the `pythia-70m` model useful. Note that `lit-gpt` supports Meta's LLaMA open-source descendent models such as Open-LLaMA (which has a 3B version) and Vicuna.

**Comment by flyman3046** [comment]
Thanks. May I ask the difference between `lit-gpt` and `lit-llama`? After a quick browse, `lit-gpt` seems to support many more models whereas `lit-llama` only supports facebook's llama?

**Comment by flyman3046** [comment]
Thanks again for your response.
