### ISSUE TITLE
Evaluate lit-llama models on open LLM leaderboard

### ISSUE THREAD

**Issue by Amshaker** [Lightning-AI/lit-llama#422]
Hi,

I have a question please, assume that I fine-tuned the Falcon model with adapters on a specific dataset and want to upload it on [openLLM leaderboard ](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard)for evaluation. The steps are clear [here](https://huggingface.co/docs/transformers/v4.15.0/model_sharing) for transformer models. How can we do the same model upload using lit-llama for evaluation on this leaderboard?

Best regards,
Abdelrahman.

**Comment by Amshaker** [comment]
@carmocca Your fast response is highly appreciated.

**Comment by carmocca** [comment]
Answered in https://github.com/Lightning-AI/lit-gpt/issues/249. Closing this one as a duplicate
