### ISSUE TITLE
How to make torch.compile work with lit-llama ? 

### ISSUE THREAD

**Issue by xsyourpal** [Lightning-AI/lit-llama#426]
I am looking for some help in figuring out what needs to be done to be able to run the pretain/redpajamas.py script with following uncommented.     
if compile:
        model = torch.compile(model):

Currently it generates several errors like "AssertionError: create_node using arg not from this SubgraphTracer"  among others.  I can provide detailed output if it helps.

My goal is to run 7B model across 8 GPUs with FSDP with torch.compile True

I am using 8 A100 GPUs,  Torch Lightning version 2.1.0dev and  Torch version: 2.1.0.dev20230713 Python version: 3.11.4 in conda environment.  I am running the following script
python pretrain/redpajama.py --devices 2 --train_data_dir data/lit-redpajama-sample

Thank You

**Comment by carmocca** [comment]
Hi!the PyTorch core team was working (at some point) on improving support for `torch.compile` with lit-llama. I believe there were several bug-fixes that landed so you will definitely want to install PyTorch nightly to use it.

If you encounter any other issues like the one you shared, your best bet would be to post a reproduction script in the PyTorch's github issues page.

Hope this helps!

**Comment by xsyourpal** [comment]
@carmocca  Thank You.   I will follow PyTorch issues page for any updates related to this.  I am already using PyTorch Nightly  so it probably something that is WIP.
I did find "Model compilation support #62" (https://github.com/Lightning-AI/lit-llama/issues/62) somewhat related, but am not sure if that discussion is still applicable to the current version of lit-llama

Appreciate your help.

**Comment by cxxgtxy** [comment]
> @carmocca Thank You. I will follow PyTorch issues page for any updates related to this. I am already using PyTorch Nightly, it is probably something that is WIP. I did find "Model compilation support" (#62) related, but am not sure if that discussion is still applicable to the current version of lit-llama
> 
> Appreciate your help.

I encounter the same problem. I'm looking forward to your further update. Thanks@
