### ISSUE TITLE
Doesn't work with batched input

### ISSUE THREAD

**Issue by patrickvonplaten** [Lightning-AI/lit-llama#49]
It seems like the generate method doesn't work with batched input no - it only accepts an input of type `str`

**Comment by awaelchli** [comment]
@patrickvonplaten 

The generate method inside of generate.py accepts a batched input. The docstring says:

```py
idx: Tensor of shape (B, T) with indices of the prompt sequence.
```
This is the tokenized version of the string.

You can actually see how it gets passed to this method here: https://github.com/Lightning-AI/lit-llama/blob/9810b07ce74a811c3682cee5be6b0d3da15877aa/generate.py#LL122C6-L122C6 

where we just add the batch dimension. The generate.py is meant to be run as a simple script with a simple prompt as input from the command line like shown in the README. But if you want, you can also import the function and use it for a batched input. 

Alternatively, one could also move the tokenization into the generate function and make it accept a list of strings.

**Comment by lantiga** [comment]
Ok to close this @patrickvonplaten ?

**Comment by carmocca** [comment]
> Alternatively, one could also move the tokenization into the generate function and make it accept a list of strings.

We could add on more function for this that basically contains this piece of code: https://github.com/Lightning-AI/lit-llama/blob/f808df1971cbac345b3d8de263a251374a53d5e9/generate.py#L120-L136 with support for multiple prompts

But if we feel like the change would add unnecessary misdirection, then we can close this issue.

**Comment by patrickvonplaten** [comment]
Ok to close, just note that batched generation probably also need things like left-padding, e.g. if samples are of different lengths, then the padding should be added on the let

`[["hey"], ["hey this is"]]` => `[[0, 0, 34], [34, 2, 3]]`

Might be worth adding some helping util for this, but ok to close

**Comment by lantiga** [comment]
Closing as we removed batch generation support to make the generation code simpler.
Happy to add a separate batched generation script later on if the need emerges.
