### ISSUE TITLE
Apache - 2.0 - Commercial License

### ISSUE THREAD

**Issue by Rock-Anderson** [Lightning-AI/lit-llama#50]
Hey team, 
Thanks for releasing the code and repo under Apache-2.0 

I'm still wondering though, as to how this would be truly open-sourced and commercialisable, if we're still loading official Llama weights (under GPL License) and converting them into Lit-Llama weights? 

Or does it only mean that if we train from scratch using this code instead, without using the official Llama weights, then the end model could be used for commercial purposes? 

Please help clarify. 
TIA.

**Comment by awaelchli** [comment]
The goal of the project is to end up with weights trained from scratch yes. The license on this repo is for the source code, we don't distribute the checkpoints from Meta. So yes users need to get them through the form and can use it only for research purposes as stated there in the agreement. This is temporary until we have checkpoints of our own trained with the code here (see bullet point list in readme :))

**Comment by lantiga** [comment]
@Rock-Anderson on top of what @awaelchli said:

> if we're still loading official Llama weights (under GPL License)

note that the LLaMA weights from Meta are **not** GPL licensed. They are released under a custom Meta license:

> To maintain integrity and prevent misuse, we are releasing our model under a noncommercial license focused on research use cases. Access to the model will be granted on a case-by-case basis to academic researchers; those affiliated with organizations in government, civil society, and academia; and industry research laboratories around the world. People interested in applying for access can find the link to the application in our research paper.

_from https://ai.facebook.com/blog/large-language-model-llama-meta-ai/_

**Comment by awaelchli** [comment]
> Maybe adding that loading-weights and conversion to Lit-Llama for inference is only for research purposes, would help.

@lantiga Do we want to change the wording in the "use the model" section to mention "for research purposes only" as suggested?
