### ISSUE TITLE
Is it possible to replace MHA with FlashAttention?

### ISSUE THREAD

**Issue by siriusctrl** [Lightning-AI/lit-llama#57]
For better performance as Flash Attention is officially supported in torch 2.0

**Comment by lantiga** [comment]
Sure! Want to send a PR? :-)

**Comment by siriusctrl** [comment]
> Sure! Want to send a PR? :-)

Of course, I'm happy to do it! Please don't mind if I do it a little bit slow.

**Comment by lantiga** [comment]
Go for it 💪 and no pressure! 
And don’t forget to out here or on discord if you’re stuck

**Comment by siriusctrl** [comment]
No problem. Already joined the discord channel and will definitely reach out to you guys if I need some help!

**Comment by siriusctrl** [comment]
> Go for it 💪 and no pressure! And don’t forget to out here or on discord if you’re stuck

By closely looking at the code, I realize that the current version already used flash attention. I'll close this issue and thanks for the great code.😂
https://github.com/Lightning-AI/lit-llama/blob/f808df1971cbac345b3d8de263a251374a53d5e9/lit_llama/model.py#L128-L129

**Comment by lantiga** [comment]
Yes it does, my bad, I thought there was another/more optimized recent version of it somehow
Thanks for the proposal anyway @siriusctrl
