### ISSUE TITLE
The model weights are still based on the official LLaMA repository. It makes it not really possible to use lit-llama for commercial use.

### ISSUE THREAD

**Issue by tguo-1** [Lightning-AI/lit-llama#58]

**Comment by lantiga** [comment]
Yes this is the case and it is clearly stated in the README

> To generate text predictions, download the model weights following the instructions on the official [LLaMA repository](https://github.com/facebookresearch/llama). Note that currently the weights are still under a [research-only license](https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md#model-details), there's no change to that (yet 🤓).
