### ISSUE TITLE
This is a brazen insult to open source community 

### ISSUE THREAD

**Issue by ethanyanjiali** [Lightning-AI/lit-llama#72]
Meta released LLLaMA under GPLv3, you took their code did some irrelevant changes and claim it to be yours and relicensed it. You could also do the same to other open source contributors, steal their work and rebrand it as yours. As a company, you also ignored the safety issue from LLaMA and just want to promote your framework without putting any safety measures. Shame on you.

**Comment by lantiga** [comment]
@ethanyanjiali I think you are grossly misrepresenting what we did.

As the paper describes, LLaMA is essentially GPT with 2 modifications: rotary encoding and RMSNorm.

As you can see from the source code (it's out there, you can look at it), what we did is 
- start from github.com/karpahty/nanoGPT (Apache 2.0)
- add rotary encoding starting *from the RoPE paper implementation* (see reference in the source code)
- add RMSNorm starting from *from the RMSNorm paper implementation* (see reference in the source code)
We share zero code with the original implementation.

I don't understand your remark on safety issues though. I haven't seen any implementation that addresses safety (original repo, HF transformers, gpt-neox), and on top of that we are not distributing weights.
