### ISSUE TITLE
Question: about left padding

### ISSUE THREAD

**Issue by ricardorei** [Lightning-AI/lit-llama#77]
if the model is padded to the left and its a casual language model does that mean that padding tokens will receive attention from the rest of the sequence?

Should there me a mask to prevent tokens to attend to padding?

**Comment by awaelchli** [comment]
@ricardorei Yes I think so. Note [here ](https://github.com/Lightning-AI/lit-llama/blob/e25146383221ead54e0b90d2df767c13fd2a3839/finetune.py#L178)I am padding the labels with -1 and excluding the padded part from the loss [here ](https://github.com/Lightning-AI/lit-llama/blob/e25146383221ead54e0b90d2df767c13fd2a3839/finetune.py#L160)(ignore_index=-1)
I think this part is correct but I think your comment is right. I looked back at the [original Llama](https://github.com/facebookresearch/llama/blob/main/llama/model.py) and I'm not exactly sure how they handle padding there. They don't have a mask it seems.

**Comment by ricardorei** [comment]
It seems like they have a mask [here](https://github.com/facebookresearch/llama/blob/main/llama/model.py#L229) 

and it seems like that mask is then summed to the attention scores [here](https://github.com/facebookresearch/llama/blob/main/llama/model.py#L142) which basically makes the soft-max ignore those tokens.

I think the same thing should be applied in lit-llama, specially during fine-tuning.

**Comment by ricardorei** [comment]
I guess [L142](https://github.com/Lightning-AI/lit-llama/blob/main/lit_llama/model.py#L129) needs to be changed to take that into consideration

**Comment by awaelchli** [comment]
It looks like it but this looks incorrect to me. The meaning of start_pos as a single int is strange. Afterall, we will have a batch of sequences with different length coming in, and so the amount of padding is different per minibatch sample.

**Comment by ricardorei** [comment]
I'll investigate this further and I'll keep you updated

**Comment by awaelchli** [comment]
What confused me also is that it seems other projects don't care about this (or maybe they do and don't see where). For example, the alpaca-lora applies padding through the transformers datacollator [here](https://github.com/tloen/alpaca-lora/blob/main/finetune.py#L250) but it seems this collator never modifies the attention mask. 

Regardless, I think we should explore this. How about we accept the mask directly as input to LLaMA.forward?

**Comment by awaelchli** [comment]
A second set of eyes is definitely appreciated here! Thanks for your comments so far.

**Comment by ricardorei** [comment]
Yep I think LLaMA.forward should receive the mask as optional argument and then be passed to the [scaled_dot_product_attention](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html). Other option is to use right padding.. in theory it should not affect the model. I honestly don't know why Meta likes left padding... the only two models I have seen with left padding are LASER and LLaMA

**Comment by awaelchli** [comment]
Would you be interested to send a PR for that?

**Comment by ricardorei** [comment]
I'll test both solutions tomorrow (right padding and left-padding with mask) and I can open a PR if it works.

Regardless of this issue, I really like this project. It's really simple it is a great introduction to Fabric and FSDP training. Good job for the team!

**Comment by ricardorei** [comment]
Passing an attention mask to the scaled_dot_product_attention is actually not allowed...
`RuntimeError: _scaled_dot_product_attention: Explicit attn_mask should not be set when is_causal=True`

I am trying right padding instead.

**Comment by ricardorei** [comment]
I just tried left-padding, right-padding and no padding. My results are:

Loss for left-padding: 6.5312
Loss for right-padding: 2.5107
Loss without padding: 2.5105

I did this with a batch of size 1 with 90 padding tokens

Definitely with _scaled_dot_product_attention  we should use right padding.

**Comment by ricardorei** [comment]
Ill change the padding to the right and let the model train to check how well it goes.

**Comment by lantiga** [comment]
Sounds great @ricardorei

**Comment by lantiga** [comment]
Hey @ricardorei how is right padding working for you?

**Comment by diegomontoya** [comment]
@ricardorei  Would also love to see the results on left vs right padding. Various llama projects are scattered with both left and right and frankly, I have no idea why. Your results may shed light which is the best one to use.
