### ISSUE TITLE
How to fine tune llama with peft?

### ISSUE THREAD

**Issue by imrankh46** [Lightning-AI/lit-llama#82]
I have a dataset, I try  the openai embading but they are not  good. However I want to fine tune lllama with peft on single consumer gpu. 

So, how to do this ?

**Comment by awaelchli** [comment]
LLaMA is a decoder-style transformer based on GPT. The modifications to the architecture are described in the [paper](https://arxiv.org/pdf/2302.13971v1.pdf). And the code for the whole model is [here](https://github.com/Lightning-AI/lit-llama/blob/main/lit_llama/model.py).

**Comment by imrankh46** [comment]
> LLaMA is a decoder-style transformer based on GPT. The modifications to the architecture are described in the [paper](https://arxiv.org/pdf/2302.13971v1.pdf). And the code for the whole model is [here](https://github.com/Lightning-AI/lit-llama/blob/main/lit_llama/model.py).

I will try to use bitstandbytes library. Thank you.
