### ISSUE TITLE
How  to Convert the weights from Huggleface format to the Lit-LLaMA format

### ISSUE THREAD

**Issue by zhangsanfeng86** [Lightning-AI/lit-llama#87]
Hi ,

Thank you for release code!

Could you share the script that How  to Convert the weights from Huggleface format to the Lit-LLaMA format?

**Comment by lantiga** [comment]
Duplicate of #64 

We don't have the script right now but we'll be adding it asap

**Comment by zhangsanfeng86** [comment]
Thanks for your reply!

**Comment by timothylimyl** [comment]
@lantiga , is there a reverse? lit-llama to hugging face.

**Comment by carmocca** [comment]
@timothylimyl Not at the moment. See https://github.com/Lightning-AI/lit-llama/issues/150
