### ISSUE TITLE
Loading the 13B checkpoint

### ISSUE THREAD

**Issue by ricardorei** [Lightning-AI/lit-llama#93]
Hi!

I was trying to load the 13B model checkpoint but it seems that there is a mismatch between dimensions:

e.g:
```
size mismatch for transformer.h.39.mlp.c_proj.weight: copying a param with shape torch.Size([5120, 6912]) from checkpoint, the shape in current model is torch.Size([5120, 13824]).
```

**Comment by lantiga** [comment]
is this the original 13B?

**Comment by ricardorei** [comment]
I think so. 

I downloaded the weights a few weeks ago but I used them without problems for the 7B model. The 13B model is the one raising shape mismatches.

**Comment by lantiga** [comment]
Yep, I can reproduce. Conversion succeeds but loading fails, thanks for the heads up.

**Comment by lantiga** [comment]
@ricardorei just submitted a fix

**Comment by ricardorei** [comment]
Thanks @lantiga will try it!
