### ISSUE TITLE
Politically Kind License Wording

### ISSUE THREAD

**Issue by xloem** [Lightning-AI/lit-llama#94]
Hi,

This seems like a really wonderful project for which I am thankful.

I personally support the GPL and don’t see it as preventing academic or commercial use at all.

When I read the wording in the readme that the GPL prevents these things, and is a problem to be solved (rather than a solution to problems), I feel pain. I don’t understand why or how these things would be. The function of the GPL is to keep derivative works open source. Do academic institutions need to keep their source code private?

Would you be willing to cite where these opinions stem from, and/or state the expression as opinion rather than fact?

**Comment by lantiga** [comment]
Thank you @xloem for your kind words on the project. I just tweaked the wording to sound less controversial, but the main facts stand.

While GPL doesn't prevent commercial use per se (you can still charge while releasing your code as GPL), but it is a fact that it is a) incompatible with the vast majority of the DL ecosystem b) most companies will reject codebases where GPL is used in total or in part (past personal experience - I'm aware of Linux or GNU).

On the other hand, I currently see no evidence that adopting non-viral licenses is curbing openness (see the rest of the ecosystem)


There's another, way more gnarly aspect, that it's borderline academic but not so much.

Today you can use GCC (the GNU compiler, GPL licensed) to compile non-free programs. But the GPL license *does not* allow that, the way it is written. The ability to compile non-free programs with GCC is given to you through an *explicit exception*: https://www.gnu.org/licenses/gcc-exception-3.1-faq.html.

Now, you could argue that training a model is akin compiling a program (see Karpathy's software 2.0 take). Or you may not, there's still a lot of confusion there, even on whether you can actually protect model weights (see litigations around llama weights). Not sure how this will pan out or if it will ever pan out :-) but a non-viral license is a very sane bet IMO.
